[global]
# Configuraci贸n global de Streamlit

[theme]
# Tema personalizado para CEAPSI
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
# Configuraci贸n del servidor
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
# Configuraci贸n del navegador
gatherUsageStats = false

[logger]
# Configuraci贸n de logging
level = "info"
